# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

from CompilerUi.CodeEditor import CodeEditor


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 555))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SourcePcodeVerticalLayout = QtWidgets.QVBoxLayout()
        self.SourcePcodeVerticalLayout.setObjectName("SourcePcodeVerticalLayout")
        self.SourcePcodeHorizontalLayout = QtWidgets.QHBoxLayout()
        self.SourcePcodeHorizontalLayout.setObjectName("SourcePcodeHorizontalLayout")
        self.lineNumhorizontalLayout = QtWidgets.QHBoxLayout()
        self.lineNumhorizontalLayout.setSpacing(0)
        self.lineNumhorizontalLayout.setObjectName("lineNumhorizontalLayout")
        self.sourceCodePlainTextEdit = CodeEditor(self.centralwidget)
        self.sourceCodePlainTextEdit.setObjectName("sourceCodePlainTextEdit")
        self.lineNumhorizontalLayout.addWidget(self.sourceCodePlainTextEdit)
        self.lineNumhorizontalLayout.setStretch(0, 16)
        self.SourcePcodeHorizontalLayout.addLayout(self.lineNumhorizontalLayout)
        self.pcodePlainTextEdit = CodeEditor(self.centralwidget)
        self.pcodePlainTextEdit.setReadOnly(True)
        self.pcodePlainTextEdit.setObjectName("pcodePlainTextEdit")
        self.SourcePcodeHorizontalLayout.addWidget(self.pcodePlainTextEdit)
        self.SourcePcodeHorizontalLayout.setStretch(0, 8)
        self.SourcePcodeHorizontalLayout.setStretch(1, 3)
        self.SourcePcodeVerticalLayout.addLayout(self.SourcePcodeHorizontalLayout)
        self.ErrortextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.ErrortextBrowser.setReadOnly(True)
        self.ErrortextBrowser.setOpenExternalLinks(False)
        self.ErrortextBrowser.setOpenLinks(False)
        self.ErrortextBrowser.setObjectName("ErrortextBrowser")
        self.SourcePcodeVerticalLayout.addWidget(self.ErrortextBrowser)
        self.SourcePcodeVerticalLayout.setStretch(0, 7)
        self.SourcePcodeVerticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.SourcePcodeVerticalLayout)
        self.mainVerticalLayout = QtWidgets.QVBoxLayout()
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.tableTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.tableTextEdit.setReadOnly(True)
        self.tableTextEdit.setObjectName("tableTextEdit")
        self.mainVerticalLayout.addWidget(self.tableTextEdit)
        self.tableSelectHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.tableSelectHorizontalSlider.setMaximum(3)
        self.tableSelectHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tableSelectHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.tableSelectHorizontalSlider.setObjectName("tableSelectHorizontalSlider")
        self.mainVerticalLayout.addWidget(self.tableSelectHorizontalSlider)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainVerticalLayout.addItem(spacerItem)
        self.prodocePcodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.prodocePcodeButton.setObjectName("prodocePcodeButton")
        self.mainVerticalLayout.addWidget(self.prodocePcodeButton)
        self.ButtonHorizontalLayout = QtWidgets.QHBoxLayout()
        self.ButtonHorizontalLayout.setObjectName("ButtonHorizontalLayout")
        self.showTablePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.showTablePushButton.setObjectName("showTablePushButton")
        self.ButtonHorizontalLayout.addWidget(self.showTablePushButton)
        self.runPcodePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.runPcodePushButton.setObjectName("runPcodePushButton")
        self.ButtonHorizontalLayout.addWidget(self.runPcodePushButton)
        self.mainVerticalLayout.addLayout(self.ButtonHorizontalLayout)
        self.mainVerticalLayout.setStretch(0, 8)
        self.mainVerticalLayout.setStretch(1, 1)
        self.mainVerticalLayout.setStretch(2, 2)
        self.mainVerticalLayout.setStretch(3, 2)
        self.mainVerticalLayout.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.mainVerticalLayout)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionSaveFile = QtWidgets.QAction(MainWindow)
        self.actionSaveFile.setObjectName("actionSaveFile")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSavePcode = QtWidgets.QAction(MainWindow)
        self.actionSavePcode.setObjectName("actionSavePcode")
        self.menu.addAction(self.actionNewFile)
        self.menu.addAction(self.actionOpenFile)
        self.menu.addAction(self.actionSaveFile)
        self.menu.addAction(self.actionSaveAs)
        self.menu.addAction(self.actionSavePcode)
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.runPcodePushButton.clicked.connect(MainWindow.runPcode)
        self.tableSelectHorizontalSlider.valueChanged['int'].connect(MainWindow.changeTable)
        self.showTablePushButton.clicked.connect(MainWindow.showTable)
        self.prodocePcodeButton.clicked.connect(MainWindow.producePcode)
        self.menubar.triggered['QAction*'].connect(MainWindow.menubarTriggle)
        self.sourceCodePlainTextEdit.cursorPositionChanged.connect(MainWindow.updateColLine)
        self.ErrortextBrowser.anchorClicked['QUrl'].connect(MainWindow.showError)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pl0文法编译器"))
        self.prodocePcodeButton.setText(_translate("MainWindow", "生成Pcode"))
        self.prodocePcodeButton.setShortcut(_translate("MainWindow", "F5"))
        self.showTablePushButton.setText(_translate("MainWindow", "显示符号表"))
        self.showTablePushButton.setShortcut(_translate("MainWindow", "F6"))
        self.runPcodePushButton.setText(_translate("MainWindow", "运行Pcode"))
        self.runPcodePushButton.setShortcut(_translate("MainWindow", "Ctrl+F5"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.actionOpenFile.setText(_translate("MainWindow", "打开文件"))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNewFile.setText(_translate("MainWindow", "新建文件"))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSaveFile.setText(_translate("MainWindow", "保存文件"))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "另存为"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionAbout.setText(_translate("MainWindow", "关于作者"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionSavePcode.setText(_translate("MainWindow", "保存Pcode"))
        self.actionSavePcode.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))

